name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        run: |
             cd frontend &&
             sudo npm install --save react react-dom react-scripts &&
             sudo npm run build 
            

      - name: Build Backend
        run: |
             cd backend &&
             sudo npm install

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            echo "$SSH_PRIVATE_KEY" > private_key
            chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@18.204.220.41 "
            cd /var/www/myapp &&
            rm -rf frontend/build &&
            cp -r myapp/frontend/build /var/www/myapp/frontend &&
            npm i pm2 -g &&
            cd backend
            pm2 start server.js"
        
  
