name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        run: |
             cd frontend &&
             sudo npm install --save react react-dom react-scripts &&
             sudo npm run build 
            

      - name: Build Backend
        run: |
             cd backend &&
             sudo npm install

      - name: Deploy to Server
        run: |
          ssh -i $SSH_PRIVATE_KEY ubuntu@54.165.95.45 "
            cd /var/www/myapp &&
            rm -rf frontend/build &&
            cp -r myapp/rontend/build /var/www/myapp/frontend &&
            npm i pm2 -g &&
            cd backend
            pm2 start server.js
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
